### ISSUE TITLE
Scavenge method 

### ISSUE THREAD

**Issue by kmalakoff** [nicdex/node-eventstore-client#38]
I would like to be able to run scavenge after hard deleting streams when automating unit tests so the streams are fully removed.

**Comment by nicdex** [comment]
I can implement the method but it will not have the desired effect. Running a scavenge won't delete the latest data.

"Scavenges only affect completed chunks, so deleted events in the current chunk will still be there after you run a scavenge." from http://docs.geteventstore.com/server/3.9.0/scavenging/

**Comment by kmalakoff** [comment]
Great! I would love to see this. 

It is just a way to clearly clear the store between tests and works for me when running manually after a delete so works for me.

**Comment by nicdex** [comment]
It wasn't a suggestion it's a fact stated in the documentation, the url and quote I posted in my previous post. Adding screen capture of the warning. The fact that scavenging worked once is a fluke, it's not guaranteed to work because of that warning and how scavenging/$all work. I did the same tests myself and running a scavenge did not remove the events from $all.

![image](https://cloud.githubusercontent.com/assets/4165723/26765731/03fa343c-4937-11e7-80bc-5e78cde87e19.png)

**Comment by kmalakoff** [comment]
Hmmmm. I guess the documentation is inconsistent then and it's not the solution I'm looking for. 

I opened an issue with event store and hopefully they can be convinced that there should be a way to do a clean and deterministic reset of the event store.

Thank you for checking and doublechecking this Nic!

Closing...
