### ISSUE TITLE
Exception when retrieving RecordedEvents

### ISSUE THREAD

**Issue by sledorze** [nicdex/node-eventstore-client#45]
I got a ```TypeError: ev.createdEpoch.toNumber is not a function```
from here:
https://github.com/nicdex/node-eventstore-client/blob/83cfa8fe1c17c2827fe4cff88629ae7775429b9f/src/results.js#L60

Inspecting the value reveals,```createdEpoch``` is a ```number``` hence the crash.

I'm wondering if I'm doing something wrong because how simple I made it crash.
What type was it supposed to be?

**Comment by nicdex** [comment]
It is supposed to be marshalled as a Long (from https://www.npmjs.com/package/long) from protobuf.

**Comment by nicdex** [comment]
I updated the protobufjs recently, but all my tests are passing and I didn't see any issue with the projects using the library. What action are you actually using?

**Comment by nicdex** [comment]
@sledorze Apparently protobufjs will marshall as Number instead of Long if the long.js library is not present. So make sure that node_modules/long folder is there. This might be an issue with npm not fetching node-eventstore-client dependencies. In worst case add "long": "^3.2" to your package.json and it will fix it.

**Comment by sledorze** [comment]
@nicdex Oh.. that's it definitively it, thanks!
