### ISSUE TITLE
Indicate if/how backpressure is/would be handled on subscriptions.

### ISSUE THREAD

**Issue by sledorze** [nicdex/node-eventstore-client#47]
This becomes a fundamental concern when replaying events with a slow consumer endpoint.

**Comment by nicdex** [comment]
Sorry about the delayed answer, for some reason this issue didn't show up in my emails.

In most of the case you should return a promise from EventAppearedCallback, because events need to be processed in order and most of handlers storing data are "async". A catchup subscription is passed a batchSize as its last parameter, it defaults to 500. Meaning that 500 events will be read and need to be processed before the next batch is read and processed. This of course only apply to the "catchup" portion of the subscription, once a subscription is live events will build up in the "to be processed" queue if the handler is really slow.

Does it answer your question?

**Comment by sledorze** [comment]
@nicdex that's the thing, yes, you've answered it.
So if I understood well, the remaining issue with back pressure here is that this queue can grow indefinitely in memory and exhaust the available RAM, am I right?

**Comment by nicdex** [comment]
Remember this is only for live events. So you would need to have a very fast producer and very slow consumer for this to be a problem. If that's the case, you'll need to add you own queue management in your application. Once the queue reach the high limit you can stop the subscription and start it again once it reach the lower limit.

**Comment by sledorze** [comment]
@nicdex Yes that's exactly what I wanted to know, thanks.
So from your explanation, I understand that it's not the scope of this library but the answer you gave may help implementing it on top of the existing lib. (modulo one can shut up the subscription fast enough to not be overwhelmed)
