### ISSUE TITLE
Test if a persistentSubscription already exists

### ISSUE THREAD

**Issue by sledorze** [nicdex/node-eventstore-client#55]
It seems there's no way to check for persistent subscription existence.
Could it be exposed? (also in Typescript)

**Comment by nicdex** [comment]
It is not something that exists in the original .Net client. There the HTTP /subscriptions endpoint but it's undocumented. You could try to write your own side client to query it.

**Comment by sledorze** [comment]
Oh I was not expecting that.. thanks for the feedback (and the great lib effort!)

**Comment by nicdex** [comment]
Sorry if my answer seemed harsh. This client mostly focus on the TCP API not the HTTP API.
That being said the ProjectionManager (which use only HTTP) was added because it's also in the .Net client (which I try to mimic to follow compatibility).

I actually found out that the subscriptions HTTP API is partially documented at https://eventstore.org/docs/http-api/competing-consumers/. I say partially because they show JSON response format, but they do not document HTTP status code the endpoint returns if the subscription requested doesn't exists.

Again any help is appreciated, if you want to add an external client class for this feature you are welcome to do so. I accept PR, even in typescript ;)
