### ISSUE TITLE
Feature: Describe Subscription

### ISSUE THREAD

**Issue by quorak** [nicdex/node-eventstore-client#71]
Hey there,

it would be great to have a convenience method to get all informations about subscriptions:
https://eventstore.org/docs/http-api/swagger/Subscriptions/Get%20all%20subscriptions.html

best

**Comment by nicdex** [comment]
Hi quorak,

Sorry but I'm in no rush to implement these "extra" features, because they're from the HTTP API and I focus on supporting/implementing the TCP based features first. Also since it's HTTP based it can easily be implemented in your application with a library like axios.

I will accept at PR if you want to give it a go.
You can use the C# code as a base https://github.com/EventStore/EventStore/tree/master/src/EventStore.ClientAPI/PersistentSubscriptions

**Comment by quorak** [comment]
cool. I will try to find time and help implementing this.
