### ISSUE TITLE
strict-event-emitter-types should be a normal dependency

### ISSUE THREAD

**Issue by MajorBreakfast** [nicdex/node-eventstore-client#73]
Recently the `strict-event-emitter-types` package was removed as a dependency. This causes an issue when using `node-eventstore-client` in a TypeScript project because the required type dependency is not installed with the other dependencies.

It is imported here in `index.d.ts`:
https://github.com/nicdex/node-eventstore-client/blob/7e5327c278729eeeddf8fe2f51b7d78cb0c3d4b5/index.d.ts#L5

Here's a discussion that I found on stack overflow about whether type dependencies go into dev or normal dependencies:
https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

I'd be great if the dependency could be added back again. As a quick fix, it is possible to install the missing dependency manually, but this solution is obviously not as clean as having it installed the normal way.

**Comment by nicdex** [comment]
Sorry about that, I'm not using the library with TypeScript so it's possible the definition are not working for all cases or in this case are not installing dependencies properly. I rely on PR and feedback to maintain them. The StrictEventEmitter was added as a PR and of course it worked in the repo because the dev dependencies were there.

Thanks about the stackoverflow link it clears things up. I will move the types definition from dev to normal dependencies and that should fix this issue.

**Comment by nicdex** [comment]
Looking into fixing some other issues and probably will do a release end of this week.

**Comment by nicdex** [comment]
Note: doing this caused #79
