### ISSUE TITLE
Endpoint to reset projctions

### ISSUE THREAD

**Issue by Poimen** [nicdex/node-eventstore-client#75]
The projection manager (and internal client) does not seem have a function to reset a projection.

The Event Store endpoint would be:
```
/projection/{name}/command/reset?enableRunAs={enableRunAs}
```

Have I missed this functionality?

**Comment by nicdex** [comment]
This functionality is new in v5. Client is only up-to-date with v4.
I have no timeline on this, since I'm real busy with work. 
PR are welcomed.

Also the projection "manager" is only a very simple wrapper around an HTTP post. So you can just do that instead if you don't feel like writting a PR or waiting for it to be done.

**Comment by Poimen** [comment]
Sure - created PR for this. I haven't had time to do much testing, but will continue next week probably.

**Comment by Poimen** [comment]
Found some time today to test this - appears to be working :)
