### ISSUE TITLE
Extra options when deleting projections

### ISSUE THREAD

**Issue by Poimen** [nicdex/node-eventstore-client#76]
When we delete a projection from the Event Store UI, we normally select all the delete options to completely clear the projection (followed by a scavenge).

From the projection client, the delete seems to only delete the emitted streams:
```javascript
ProjectionsClient.prototype.delete = function(httpEndPoint, name, deleteEmittedStreams, userCredentials) {
  return this.sendDelete(httpEndPoint + '/projection/' + name + '?deleteEmittedStreams=' + deleteEmittedStreams, userCredentials, HTTP_OK);
};
```

The Event Store documentation lists all the other options:
```
/projection/{name}?deleteStateStream={deleteStateStream}&deleteCheckpointStream={deleteCheckpointStream}&deleteEmittedStreams={deleteEmittedStreams}
```

If possible, can the api options be extended to expose the extra options?

**Comment by nicdex** [comment]
Same answer as #75.

---
This functionality is new in v5. Client is only up-to-date with v4.
I have no timeline on this, since I'm real busy with work.
PR are welcomed.

Also the projection "manager" is only a very simple wrapper around an HTTP post. So you can just do that instead if you don't feel like writting a PR or waiting for it to be done.

**Comment by Poimen** [comment]
Found some time today to test this - appears to be working :)
