### ISSUE TITLE
Implement Projections in TCP

### ISSUE THREAD

**Issue by MeenaAlfons** [nicdex/node-eventstore-client#83]
TCP is best for performance. I guess Projections can also be implemented in TCP.

I would be happy to implement it, if you give me some guidance.

**Comment by nicdex** [comment]
Are you talking about subscribing to a projection because that's already possible. If you're talking about managing projections I don't think there's a tcp API for that unless they added one in version 5.

Sent from Yahoo Mail on Android 
 
  On Fri., 26 Jul. 2019 at 1:25 p.m., Meena Alfons<notifications@github.com> wrote:   
TCP is best for performance. I guess Projections can also be implemented in TCP.

I would be happy to implement it, if you give me some guidance.

**Comment by MeenaAlfons** [comment]
I'd like to read partition state for projections. Currently, it is part of the Projections Manager. From my perspective, reading the state of a projection is not managing a projection.

I tried to find the ultimate document of what is supported in TCP and what is supported in HTTP but I couldn't. So I don't know if reading partition state can be done in TCP or not.

**Comment by MeenaAlfons** [comment]
I found that there is a stream for the results of a projection named: `$projections-{projectionName}-{partitionName}-result`.

I can read the last event in this stream to get the result of a specific partition in a projection.

This solved my problem.

**Comment by nicdex** [comment]
Great.

FYI here's are the TCP message supported by EventStore as of version 5.0.2
https://github.com/EventStore/EventStore/blob/oss-v5.0.2/src/Protos/ClientAPI/ClientMessageDtos.proto
