### ISSUE TITLE
One subscription, multiple streams?

### ISSUE THREAD

**Issue by justin-capalbo** [nicdex/node-eventstore-client#84]
Little bit confused about something - When I'm making a projection in EventStore I have access to something called fromStreams(streams: string[]).  

This is great because I can get events just from the two streams my projection cares about.  With this client I'm not sure the same capability exists.  It seems like subscribeToStream (singular) and subscribeToAll are the only options.  subscribeToAll is painfully slow because of the built in streams that eventStore provides like $stats.  Is the workaround to turn off or somehow disable these streams or is there a section of the docs I might have missed?

**Comment by nicdex** [comment]
This is not a feature provided by the clients. If you want to do this you have to create a projection stream and subscribe to it.

Sent from Yahoo Mail on Android 
 
  On Fri., 26 Jul. 2019 at 1:30 p.m., Justin C.<notifications@github.com> wrote:   
Little bit confused about something - When I'm making a projection in EventStore I have access to something called fromStreams(streams: string[]).

This is great because I can get events just from the two streams my projection cares about. With this client I'm not sure the same capability exists. It seems like subscribeToStream (singular) and subscribeToAll are the only options. subscribeToAll is painfully slow because of the built in streams that eventStore provides like $stats. Is the workaround to turn off or somehow disable these streams or is there a section of the docs I might have missed?
