### ISSUE TITLE
once('connected',...) is not called

### ISSUE THREAD

**Issue by andymel123** [nicdex/node-eventstore-client#96]
Hi, 

any idea what could be wrong if
- `on('reconnecting',...)` gets called when the eventstore is down and stops when it's up again
- `on('connected',...)` is never called
 
Copy/paste...

    // so this works
    this.esConnection.on('reconnecting', (err: any) => {
        console.error(..., err);
    });
    
    // this does not
    this.esConnection.on('connected', (tcpEndPoint: any) => {
        console.log(...);
    });

Setting `verboseLogging: true` writes logs that show the successful connection

    TcpPackageConnection: connected to [{"host":"127.0.0.1","port":1113}, L{"host":"127.0.0.1","port":51780}, 17849f78-d9d5-4403-9fb4-260fa5683029].
    ...
    EventStoreConnection 'adb->es connection (U:adb-service)': TCP connection to [{"host":"127.0.0.1","port":1113}, L{"host":"127.0.0.1","port":51780}, 17849f78-d9d5-4403-9fb4-260fa5683029] established.

But my listener function is not called.
It worked previously (have updated your node-eventstore-client(0.2.16) and the ES (5.0.6.0)), maybe that caused the problem?

**Comment by nicdex** [comment]
Sorry I tried to reproduce the issue but I can't. 
There must be something else going wrong. Can you post more info: node version, your OS, are you using docker, are you connecting to a cluster, using dns instead of IP?

I ran this, with client version 0.2.16 and EventStore 5.0.6

`
const endpoint = "tcp://localhost:1113";
const connection = client.createConnection(settings, endpoint);

connection.connect().catch(err => console.log("Connection failed", err));

connection.on("connected", tcpEndPoint =>
  console.log(`Connected to eventstore at ${tcpEndPoint.host}:${tcpEndPoint.port}`)
);

connection.on("error", error =>
  console.log(`Error occurred on connection: ${error}`)
);

connection.on("closed", reason =>
  console.log(`Connection closed, reason: ${reason}`)
);

connection.on("reconnecting", msg =>
  console.log(`Reconnecting, msg: ${JSON.stringify(msg, null, 4)}`)
);
`

and I get this output

`
Reconnecting, msg: {}
Reconnecting, msg: {}
Connected to eventstore at 127.0.0.1:1113
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Connected to eventstore at 127.0.0.1:1113
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Reconnecting, msg: {}
Connection closed, reason: Reconnection limit reached.
`

I left it timeout at the end to make that that all handlers, except error are called.

**Comment by andymel123** [comment]
Thanks a lot for your fast answer!
I copy/pasted your code in a fresh file and get the same behavior. Repeated 'reconnecting' when no ES but no 'connected'.

Any other idea how I could debug this? 
This is happening on a windows machine using the ES in Docker for Windows (image: eventstore/eventstore). The ES Admin GUI does not look like there was any problem with the Store.

**Comment by nicdex** [comment]
Sorry I could not reproduce even when using Docker. I'm using Docker Desktop on Windows 10.

**Comment by andymel123** [comment]
Hmm, damn, I will try to find time to build some minimal deployable to do more tests

**Comment by mari6274** [comment]
The same problem for me.
Node version: v12.4.0
npm version: 6.14.3
docker for MacOs: Docker version 19.03.5, build 633a0ea
MacOs: 10.14.6 Mojave

**Comment by nicdex** [comment]
This is really hard to debug since I can't reproduce. Can anyone of you give me the time correlated logs of the eventstore server, maybe there is some clue in there.

**Comment by nicdex** [comment]
I can't reproduce this on Linux or Windows

**Linux**
Ubuntu 19.10
Docker 19.03.6
Node 12.16.1
EventStore docker 5.0.7 single node
node-eventstore-client 0.12.6

**Windows**
Windows 10 1909
Docker 19.03.8
Node 12.16.1
EventStore docker 5.0.7 single node
node-eventstore-client 0.12.6

**Comment by andymel123** [comment]
I have setup a minimal project today with basically just copy and pasting code from my project and your example above. I can't see the difference yet but it works!! 
The investigation goes on...just wanted to tell you asap! :)

**Comment by andymel123** [comment]
In the eventstore log I see an entry like 
`[00001,20,05:01:59.857] SLOW QUEUE MSG ["MonitoringQueue"]: "GetFreshStats" - 940ms. Q: 0/0.`
Could that be a hint for any problem regarding the store itself or its setup that could cause troubles with the client?!

**Comment by andymel123** [comment]
Problem solved. Sorry for the false alarm!
For anyone finding this thread with a similar problem: I think in my case the center of the problem was, that the code that did the initialization happend in a promise. Maybe that's why my onconnect listener was not called (as the promise was already resolved). I am not totally sure if that's the right explanation but now that it is an observable it seems to work fine.
